<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SopSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data_sop = [
        // [
        //     'id_user' => '6',
        //     'id_status' => '5',
        //     'nomor_sop' => 'SK/RS/DIR/III/2022/002',
        //     'judul_sop' => 'SOP Hand Hygiene (Cuci Tangan)',
        //     'deskripsi' => 'Prosedur wajib untuk mencuci tangan sesuai 5 momen hand hygiene (sebelum/sesudah kontak pasien, sebelum tindakan aseptik, dsb.).',
        //     'kategori_sop' => 'SOP AP',
        //     'is_all_units' => '1',
        //     'dokumen_path' => 'sop-documents/01KC0XD5XZCPYN62RRP7S3XCXX.pdf',
        //     'tgl_pengesahan' => '2022-03-10 00:00:00',
        //     'tgl_berlaku' => '2022-03-13 00:00:00',
        //     'tgl_kadaluwarsa' => '2025-03-13 00:00:00',
        //     'tgl_review_tahunan' => '2023-03-13 00:00:00',
        //     'created_at' => now(),
        //     'updated_at' => now(),
        //     'id_unit_kerja' => '7'
        // ],
        // [
        //     'id_user' => '8',
        //     'id_status' => '1',
        //     'nomor_sop' => 'SK/RS/DIR/I/2024/005',
        //     'judul_sop' => 'SOP Penerimaan Pasien Baru Rawat Inap',
        //     'deskripsi' => 'Prosedur admission pasien, mulai dari verifikasi identitas, orientasi ruangan, hingga asesmen awal keperawatan.).',
        //     'kategori_sop' => 'SOP Internal',
        //     'is_all_units' => '0',
        //     'dokumen_path' => 'sop-documents/01KC0XD5XZCPYN62RRP7S3XCXX.pdf',
        //     'tgl_pengesahan' => '2024-01-21 00:00:00',
        //     'tgl_berlaku' => '2024-01-25 00:00:00',
        //     'tgl_kadaluwarsa' => '2027-01-25 00:00:00',
        //     'tgl_review_tahunan' => '2025-01-25 00:00:00',
        //     'created_at' => now(),
        //     'updated_at' => now(),
        //     'id_unit_kerja' => '9'
        // ],
        // [
        //     'id_user' => '7',
        //     'id_status' => '2',
        //     'nomor_sop' => 'SK/RS/DIR/VI/2025/004',
        //     'judul_sop' => 'SOP Pemberian Transfusi Darah',
        //     'deskripsi' => 'Prosedur pemeriksaan kecocokan, persiapan pasien, pemantauan, dan dokumentasi selama pemberian transfusi darah.).',
        //     'kategori_sop' => 'SOP AP',
        //     'is_all_units' => '0',
        //     'dokumen_path' => 'sop-documents/01KC0XD5XZCPYN62RRP7S3XCXX.pdf',
        //     'tgl_pengesahan' => '2025-06-01 00:00:00',
        //     'tgl_berlaku' => '2025-06-10 00:00:00',
        //     'tgl_kadaluwarsa' => '2028-06-10 00:00:00',
        //     'tgl_review_tahunan' => '2026-06-10 00:00:00',
        //     'created_at' => now(),
        //     'updated_at' => now(),
        //     'id_unit_kerja' => '8'
        // ],
        // [
        //     'id_user' => '14',
        //     'id_status' => '3',
        //     'nomor_sop' => 'SK/RS/SDM/V/2025/018',
        //     'judul_sop' => 'SOP Pengajuan Cuti Karyawan',
        //     'deskripsi' => 'Prosedur pengajuan, persetujuan, dan pencatatan semua jenis cuti karyawan (tahunan, sakit, besar, dll.)).',
        //     'kategori_sop' => 'SOP AP',
        //     'is_all_units' => '0',
        //     'dokumen_path' => 'sop-documents/01KC0XD5XZCPYN62RRP7S3XCXX.pdf',
        //     'tgl_pengesahan' => '2025-05-17 00:00:00',
        //     'tgl_berlaku' => '2025-05-19 00:00:00',
        //     'tgl_kadaluwarsa' => '2028-05-19 00:00:00',
        //     'tgl_review_tahunan' => '2026-05-19 00:00:00',
        //     'created_at' => now(),
        //     'updated_at' => now(),
        //     'id_unit_kerja' => '2'
        // ],
        // [
        //     'id_user' => '12',
        //     'id_status' => '5',
        //     'nomor_sop' => 'SK/RS/SDM/IV/2022/022',
        //     'judul_sop' => 'SOP Prosedur Pelatihan Karyawan Baru (Onboarding)',
        //     'deskripsi' => 'Prosedur orientasi dan pelatihan wajib (K3, mutu, service excellence) bagi seluruh karyawan yang baru bergabung.',
        //     'kategori_sop' => 'SOP AP',
        //     'is_all_units' => '1',
        //     'dokumen_path' => 'sop-documents/01KC0XD5XZCPYN62RRP7S3XCXX.pdf',
        //     'tgl_pengesahan' => '2022-04-18 00:00:00',
        //     'tgl_berlaku' => '2022-04-22 00:00:00',
        //     'tgl_kadaluwarsa' => '2025-04-22 00:00:00',
        //     'tgl_review_tahunan' => '2023-04-22 00:00:00',
        //     'created_at' => now(),
        //     'updated_at' => now(),
        //     'id_unit_kerja' => '22'
        // ],
        // [
        //     'id_user' => '13',
        //     'id_status' => '3',
        //     'nomor_sop' => 'SK/RS/ADM/IX/2025/016',
        //     'judul_sop' => 'SOP Klaim Asuransi Pasien',
        //     'deskripsi' => 'Prosedur lengkap untuk verifikasi keanggotaan, pengajuan klaim, dan follow-up pembayaran dari pihak asuransi/BPJS.',
        //     'kategori_sop' => 'SOP Internal',
        //     'is_all_units' => '0',
        //     'dokumen_path' => 'sop-documents/01KC0XD5XZCPYN62RRP7S3XCXX.pdf',
        //     'tgl_pengesahan' => '2025-09-17 00:00:00',
        //     'tgl_berlaku' => '2025-09-19 00:00:00',
        //     'tgl_kadaluwarsa' => '2028-09-19 00:00:00',
        //     'tgl_review_tahunan' => '2026-09-19 00:00:00',
        //     'created_at' => now(),
        //     'updated_at' => now(),
        //     'id_unit_kerja' => '20'
        // ],
        // [
        //     'id_user' => '10',
        //     'id_status' => '2',
        //     'nomor_sop' => 'SK/RS/DIR/X/2024/009',
        //     'judul_sop' => 'SOP Pengambilan Spesimen Darah Vena',
        //     'deskripsi' => 'Prosedur pengambilan sampel darah vena, termasuk persiapan alat, identifikasi pasien, dan labelisasi spesimen yang benar.',
        //     'kategori_sop' => 'SOP Internal',
        //     'is_all_units' => '0',
        //     'dokumen_path' => 'sop-documents/01KC0XD5XZCPYN62RRP7S3XCXX.pdf',
        //     'tgl_pengesahan' => '2024-10-17 00:00:00',
        //     'tgl_berlaku' => '2024-10-27 00:00:00',
        //     'tgl_kadaluwarsa' => '2027-10-27 00:00:00',
        //     'tgl_review_tahunan' => '2025-10-27 00:00:00',
        //     'created_at' => now(),
        //     'updated_at' => now(),
        //     'id_unit_kerja' => '14'
        // ],
        // [
        //     'id_user' => '9',
        //     'id_status' => '2',
        //     'nomor_sop' => 'SK/RS/DIR/XI/2024/012',
        //     'judul_sop' => 'SOP Penggunaan Alat Pelindung Diri (APD)',
        //     'deskripsi' => 'Prosedur pemilihan, cara penggunaan (donning), dan pelepasan (doffing) APD (masker, sarung tangan, gaun) yang tepat.',
        //     'kategori_sop' => 'SOP AP',
        //     'is_all_units' => '0',
        //     'dokumen_path' => 'sop-documents/01KC0XD5XZCPYN62RRP7S3XCXX.pdf',
        //     'tgl_pengesahan' => '2024-12-20 00:00:00',
        //     'tgl_berlaku' => '2024-12-23 00:00:00',
        //     'tgl_kadaluwarsa' => '2027-12-23 00:00:00',
        //     'tgl_review_tahunan' => '2025-12-23 00:00:00',
        //     'created_at' => now(),
        //     'updated_at' => now(),
        //     'id_unit_kerja' => '10'
        // ],
        // [
        //     'id_user' => '18',
        //     'id_status' => '4',
        //     'nomor_sop' => 'SK/RS/KMN/VI/2023/025',
        //     'judul_sop' => 'SOP Kebersihan dan Sanitasi Ruang Rawat Inap',
        //     'deskripsi' => 'Prosedur pembersihan lantai, perabotan, dan kamar mandi pasien secara rutin dan sesuai jadwal (pagi, sore).',
        //     'kategori_sop' => 'SOP Internal',
        //     'is_all_units' => '0',
        //     'dokumen_path' => 'sop-documents/01KC0XD5XZCPYN62RRP7S3XCXX.pdf',
        //     'tgl_pengesahan' => '2023-06-20 00:00:00',
        //     'tgl_berlaku' => '2023-06-23 00:00:00',
        //     'tgl_kadaluwarsa' => '2026-06-23 00:00:00',
        //     'tgl_review_tahunan' => '2024-06-23 00:00:00',
        //     'created_at' => now(),
        //     'updated_at' => now(),
        //     'id_unit_kerja' => '6'
        // ],
        // [
        //     'id_user' => '6',
        //     'id_status' => '4',
        //     'nomor_sop' => 'SK/RS/DIR/XI/2025/006',
        //     'judul_sop' => 'SOP Resusitasi Jantung Paru (RJP/Bantuan Hidup Dasar)',
        //     'deskripsi' => 'Prosedur segera yang harus dilakukan saat pasien mengalami henti jantung/henti napas (Dewasa, Anak, dan Bayi).',
        //     'kategori_sop' => 'SOP AP',
        //     'is_all_units' => '0',
        //     'dokumen_path' => 'sop-documents/01KC0XD5XZCPYN62RRP7S3XCXX.pdf',
        //     'tgl_pengesahan' => '2025-11-11 00:00:00',
        //     'tgl_berlaku' => '2025-11-12 00:00:00',
        //     'tgl_kadaluwarsa' => '2028-11-12 00:00:00',
        //     'tgl_review_tahunan' => '2026-11-12 00:00:00',
        //     'created_at' => now(),
        //     'updated_at' => now(),
        //     'id_unit_kerja' => '7'
        // ],
        // [
        //     'id_user' => '18',
        //     'id_status' => '1',
        //     'nomor_sop' => 'SK/RS/DIR/V/2024/013',
        //     'judul_sop' => 'SOP Sterilisasi Alat Medis',
        //     'deskripsi' => 'Prosedur pencucian, pengemasan, sterilisasi, dan penyimpanan alat medis/bedah di unit CSSD.',
        //     'kategori_sop' => 'SOP Internal',
        //     'is_all_units' => '0',
        //     'dokumen_path' => 'sop-documents/01KC0XD5XZCPYN62RRP7S3XCXX.pdf',
        //     'tgl_pengesahan' => '2024-05-13 00:00:00',
        //     'tgl_berlaku' => '2024-05-23 00:00:00',
        //     'tgl_kadaluwarsa' => '2027-05-23 00:00:00',
        //     'tgl_review_tahunan' => '2025-05-23 00:00:00',
        //     'created_at' => now(),
        //     'updated_at' => now(),
        //     'id_unit_kerja' => '6'
        // ],
        [
            'id_user' => '8',
            'id_status' => '5',
            'nomor_sop' => 'SK/RS/DIR/VII/2022/001',
            'judul_sop' => 'SOP Pemasangan Kateter Urine',
            'deskripsi' => 'Prosedur langkah demi langkah untuk pemasangan kateter urine steril pada pasien dewasa.',
            'kategori_sop' => 'SOP AP',
            'is_all_units' => '0',
            'dokumen_path' => 'sop-documents/01KC0XD5XZCPYN62RRP7S3XCXX.pdf',
            'tgl_pengesahan' => '2022-07-03 00:00:00',
            'tgl_berlaku' => '2022-07-05 00:00:00',
            'tgl_kadaluwarsa' => '2025-07-05 00:00:00',
            'tgl_review_tahunan' => '2025-07-05 00:00:00',
            'created_at' => now(),
            'updated_at' => now(),
            'id_unit_kerja' => '9'
        ],
        [
            'id_user' => '18',
            'id_status' => '4',
            'nomor_sop' => 'SK/RS/DIR/I/2024/003',
            'judul_sop' => 'SOP Penanganan Sampah Medis',
            'deskripsi' => 'Prosedur pemilahan, pengumpulan, penyimpanan sementara, dan pembuangan sampah medis infeksius dan non-infeksius.',
            'kategori_sop' => 'SOP Internal',
            'is_all_units' => '0',
            'dokumen_path' => 'sop-documents/01KC0XD5XZCPYN62RRP7S3XCXX.pdf',
            'tgl_pengesahan' => '2024-01-08 00:00:00',
            'tgl_berlaku' => '2024-01-10 00:00:00',
            'tgl_kadaluwarsa' => '2027-01-10 00:00:00',
            'tgl_review_tahunan' => '2026-01-10 00:00:00',
            'created_at' => now(),
            'updated_at' => now(),
            'id_unit_kerja' => '6'
        ],
        [
            'id_user' => '7',
            'id_status' => '4',
            'nomor_sop' => 'SK/RS/DIR/XII/2024/011',
            'judul_sop' => 'SOP Serah Terima Pasien (Handover)',
            'deskripsi' => 'Prosedur komunikasi terstruktur antar petugas (SBAR/ISBAR) saat pergantian shift atau transfer pasien.',
            'kategori_sop' => 'SOP AP',
            'is_all_units' => '0',
            'dokumen_path' => 'sop-documents/01KC0XD5XZCPYN62RRP7S3XCXX.pdf',
            'tgl_pengesahan' => '2024-12-09 00:00:00',
            'tgl_berlaku' => '2024-12-12 00:00:00',
            'tgl_kadaluwarsa' => '2027-12-12 00:00:00',
            'tgl_review_tahunan' => '2025-12-12 00:00:00',
            'created_at' => now(),
            'updated_at' => now(),
            'id_unit_kerja' => '8'
        ],
        [
            'id_user' => '11',
            'id_status' => '2',
            'nomor_sop' => 'SK/RS/DIR/II/2025/015',
            'judul_sop' => 'SOP Pengamanan Area Farmasi dan Obat High Alert',
            'deskripsi' => 'Prosedur pengamanan fisik di area penyimpanan obat dan penandaan/pengelolaan khusus untuk obat High Alert.',
            'kategori_sop' => 'SOP Internal',
            'is_all_units' => '0',
            'dokumen_path' => 'sop-documents/01KC0XD5XZCPYN62RRP7S3XCXX.pdf',
            'tgl_pengesahan' => '2025-02-10 00:00:00',
            'tgl_berlaku' => '2025-02-14 00:00:00',
            'tgl_kadaluwarsa' => '2028-02-14 00:00:00',
            'tgl_review_tahunan' => '2026-02-14 00:00:00',
            'created_at' => now(),
            'updated_at' => now(),
            'id_unit_kerja' => '13'
        ],
        [
            'id_user' => '14',
            'id_status' => '2',
            'nomor_sop' => 'SK/RS/DIR/VIII/2023/015',
            'judul_sop' => 'SOP Penerimaan Tamu dan Pihak Eksternal',
            'deskripsi' => 'Prosedur pendaftaran, pemberian kartu identitas tamu, dan pengarahan di area rumah sakit untuk pihak non-pasien.',
            'kategori_sop' => 'SOP Internal',
            'is_all_units' => '0',
            'dokumen_path' => 'sop-documents/01KC0XD5XZCPYN62RRP7S3XCXX.pdf',
            'tgl_pengesahan' => '2023-08-21 00:00:00',
            'tgl_berlaku' => '2023-08-30 00:00:00',
            'tgl_kadaluwarsa' => '2026-08-30 00:00:00',
            'tgl_review_tahunan' => NULL,
            'created_at' => now(),
            'updated_at' => now(),
            'id_unit_kerja' => '2'
        ],
        [
            'id_user' => '13',
            'id_status' => '4',
            'nomor_sop' => 'SK/RS/LOG/II/2025/030',
            'judul_sop' => 'SOP Pengadaan dan Pemeliharaan Aset Inventaris',
            'deskripsi' => 'Prosedur pengajuan pembelian aset baru (non-medis), pencatatan inventaris, dan jadwal pemeliharaan barang elektronik/perabot.',
            'kategori_sop' => 'SOP AP',
            'is_all_units' => '0',
            'dokumen_path' => 'sop-documents/01KC0XD5XZCPYN62RRP7S3XCXX.pdf',
            'tgl_pengesahan' => '2025-02-01 00:00:00',
            'tgl_berlaku' => '2025-02-03 00:00:00',
            'tgl_kadaluwarsa' => '2028-02-03 00:00:00',
            'tgl_review_tahunan' => '2026-02-03 00:00:00',
            'created_at' => now(),
            'updated_at' => now(),
            'id_unit_kerja' => '20'
        ],
        [
            'id_user' => '4',
            'id_status' => '4',
            'nomor_sop' => 'SK/RS/IT/IV/2024/037',
            'judul_sop' => 'SOP Prosedur Keamanan Siber dan Data',
            'deskripsi' => 'Prosedur backup data sistem informasi manajemen rumah sakit (SIMRS), pembaruan software, dan penanganan insiden kebocoran data.',
            'kategori_sop' => 'SOP Internal',
            'is_all_units' => '0',
            'dokumen_path' => 'sop-documents/01KC0XD5XZCPYN62RRP7S3XCXX.pdf',
            'tgl_pengesahan' => '2024-04-22 00:00:00',
            'tgl_berlaku' => '2024-04-29 00:00:00',
            'tgl_kadaluwarsa' => '2027-04-29 00:00:00',
            'tgl_review_tahunan' => '2026-04-29 00:00:00',
            'created_at' => now(),
            'updated_at' => now(),
            'id_unit_kerja' => '4'
        ],
        [
            'id_user' => '4',
            'id_status' => '3',
            'nomor_sop' => 'SK/RS/IT/XII/2025/047',
            'judul_sop' => 'SOP Backup Data Harian SIMRS',
            'deskripsi' => 'Prosedur backup data sistem informasi manajemen rumah sakit (SIMRS), pembaruan software, dan penanganan insiden kebocoran data.',
            'kategori_sop' => 'SOP Internal',
            'is_all_units' => '0',
            'dokumen_path' => 'sop-documents/01KC0XD5XZCPYN62RRP7S3XCXX.pdf',
            'tgl_pengesahan' => '2025-12-25 00:00:00',
            'tgl_berlaku' => '2025-12-25 00:00:00',
            'tgl_kadaluwarsa' => '2028-12-31 00:00:00',
            'tgl_review_tahunan' => '2026-12-31 00:00:00',
            'created_at' => now(),
            'updated_at' => now(),
            'id_unit_kerja' => '4'
        ],
        [
            'id_user' => '18',
            'id_status' => '3',
            'nomor_sop' => 'SK/RS/FMT/XI/2025/038',
            'judul_sop' => 'SOP Pengelolaan Laundry Pakaian Dinas',
            'deskripsi' => 'Prosedur pengumpulan, pencucian, sterilisasi, pelipatan, dan pendistribusian seragam bersih kepada staf dan perawat.',
            'kategori_sop' => 'SOP Internal',
            'is_all_units' => '0',
            'dokumen_path' => 'sop-documents/01KC0XD5XZCPYN62RRP7S3XCXX.pdf',
            'tgl_pengesahan' => '2025-11-27 00:00:00',
            'tgl_berlaku' => '2025-11-29 00:00:00',
            'tgl_kadaluwarsa' => '2028-11-29 00:00:00',
            'tgl_review_tahunan' => '2026-11-29 00:00:00',
            'created_at' => now(),
            'updated_at' => now(),
            'id_unit_kerja' => '6'
        ],
        [
            'id_user' => '18',
            'id_status' => '5',
            'nomor_sop' => 'SK/RS/K3L/VIII/2022/050',
            'judul_sop' => 'SOP Pengelolaan Limbah Cair dan Saluran Drainase',
            'deskripsi' => 'Prosedur pengawasan kualitas limbah cair yang masuk ke Instalasi Pengolahan Air Limbah (IPAL) dan pembersihan rutin saluran drainase untuk mencegah penyumbatan.',
            'kategori_sop' => 'SOP Internal',
            'is_all_units' => '0',
            'dokumen_path' => 'sop-documents/01KC0XD5XZCPYN62RRP7S3XCXX.pdf',
            'tgl_pengesahan' => '2022-08-27 00:00:00',
            'tgl_berlaku' => '2022-08-29 00:00:00',
            'tgl_kadaluwarsa' => '2025-08-29 00:00:00',
            'tgl_review_tahunan' => '2025-08-29 00:00:00',
            'created_at' => now(),
            'updated_at' => now(),
            'id_unit_kerja' => '6'
        ],
        [
            'id_user' => '4',
            'id_status' => '2',
            'nomor_sop' => 'SK/RS/IT/I/2024/048',
            'judul_sop' => 'SOP Pemberian Hak Akses Pengguna SIMRS',
            'deskripsi' => 'Prosedur pengajuan permintaan akun baru, penentuan level akses (role), dan pemberian password default kepada karyawan sesuai jabatan dan kebutuhan kerjanya.',
            'kategori_sop' => 'SOP AP',
            'is_all_units' => '0',
            'dokumen_path' => 'sop-documents/01KC0XD5XZCPYN62RRP7S3XCXX.pdf',
            'tgl_pengesahan' => '2024-01-05 00:00:00',
            'tgl_berlaku' => '2024-01-10 00:00:00',
            'tgl_kadaluwarsa' => '2027-01-10 00:00:00',
            'tgl_review_tahunan' => '2026-01-10 00:00:00',
            'created_at' => now(),
            'updated_at' => now(),
            'id_unit_kerja' => '4'
        ],
        [
            'id_user' => '12',
            'id_status' => '4',
            'nomor_sop' => 'SK/RS/DIKLIT/IX/2025/053',
            'judul_sop' => 'SOP Pengajuan dan Review Proposal Penelitian Staf',
            'deskripsi' => 'Prosedur formal bagi staf RS untuk mengajukan proposal penelitian, termasuk proses review oleh Komite Etik dan persetujuan Kepala Bagian Diklit.',
            'kategori_sop' => 'SOP Internal',
            'is_all_units' => '0',
            'dokumen_path' => 'sop-documents/01KC0XD5XZCPYN62RRP7S3XCXX.pdf',
            'tgl_pengesahan' => '2025-09-14 00:00:00',
            'tgl_berlaku' => '2025-09-24 00:00:00',
            'tgl_kadaluwarsa' => '2028-09-24 00:00:00',
            'tgl_review_tahunan' => '2028-09-24 00:00:00',
            'created_at' => now(),
            'updated_at' => now(),
            'id_unit_kerja' => '22'
        ],
        [
            'id_user' => '12',
            'id_status' => '2',
            'nomor_sop' => 'SK/RS/DIKLIT/X/2025/054',
            'judul_sop' => 'SOP Pelaksanaan In House Training (IHT)',
            'deskripsi' => 'Prosedur penetapan kebutuhan pelatihan, penyiapan materi, jadwal pelaksanaan, dokumentasi kehadiran, dan evaluasi efektivitas pelatihan internal staf.',
            'kategori_sop' => 'SOP AP',
            'is_all_units' => '0',
            'dokumen_path' => 'sop-documents/01KC0XD5XZCPYN62RRP7S3XCXX.pdf',
            'tgl_pengesahan' => '2025-10-14 00:00:00',
            'tgl_berlaku' => '2025-10-24 00:00:00',
            'tgl_kadaluwarsa' => '2028-10-24 00:00:00',
            'tgl_review_tahunan' => '2028-10-24 00:00:00',
            'created_at' => now(),
            'updated_at' => now(),
            'id_unit_kerja' => '22'
        ],
        [
            'id_user' => '18',
            'id_status' => '2',
            'nomor_sop' => 'SK/RS/K3L/XII/2025/051',
            'judul_sop' => 'SOP Monitoring Kualitas Udara Ruangan',
            'deskripsi' => 'Prosedur pengukuran berkala suhu, kelembaban, dan pertukaran udara (air change per hour) di ruangan vital seperti kamar operasi dan Intensive Care Unit (ICU).',
            'kategori_sop' => 'SOP AP',
            'is_all_units' => '0',
            'dokumen_path' => 'sop-documents/01KC0XD5XZCPYN62RRP7S3XCXX.pdf',
            'tgl_pengesahan' => '2025-12-05 00:00:00',
            'tgl_berlaku' => '2025-12-08 00:00:00',
            'tgl_kadaluwarsa' => '2028-12-08 00:00:00',
            'tgl_review_tahunan' => '2028-12-08 00:00:00',
            'created_at' => now(),
            'updated_at' => now(),
            'id_unit_kerja' => '6'
        ]
        ];

        DB::table('tb_sop')->insert($data_sop);
    }
}
